name:                sqids-haskell
version:             0.0.0.0
category:            Web
synopsis:            Sqids (pronounced "squids") is a small library that lets you generate YouTube-looking IDs from numbers. It's good for link shortening, fast & URL-safe ID generation and decoding back into numbers for quicker database lookups.
description:         Please see the README on GitHub at <https://github.com/sqids/sqids-haskell#readme>
github:              "github.com/sqids/sqids-haskell"
license:             MIT
license-file:        LICENSE
author:              "Heikki Johannes Hildén"
maintainer:          "hildenjohannes@gmail.com"
copyright:           "2023-present Sqids maintainers"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - text >= 2.0.2 && < 2.1.0
  - containers >= 0.6.7 && < 0.7.0
  - mtl >= 2.2.2 && < 2.3.0
  - transformers >= 0.5.6.2 && < 0.6.0.0

tests:
  sqids-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sqids-haskell
    - text >= 2.0.2 && < 2.1.0
    - containers >= 0.6.7 && < 0.7.0
    - mtl >= 2.2.2 && < 2.3.0
    - hspec >= 2.10.10 && < 2.11
    - split >= 0.2.3.5 && < 0.3.0.0
